"""Correction des doublons de modèles

Revision ID: 7b7f2948cc18
Revises: 
Create Date: 2026-09-04 20:18:42.534116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7f2948cc18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('civilites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle')
    )
    op.create_table('coproprietaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copropriete_id', sa.Integer(), nullable=False),
    sa.Column('date_acquisition', sa.Date(), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('numero_lot', sa.String(length=50), nullable=True),
    sa.Column('nature_lot', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('est_residence_principale', sa.Boolean(), nullable=True),
    sa.Column('est_loue', sa.Boolean(), nullable=True),
    sa.Column('date_envoi_mail_accueil', sa.Date(), nullable=True),
    sa.Column('lien_espace_client', sa.String(length=500), nullable=True),
    sa.Column('locataire_civilite_id', sa.Integer(), nullable=True),
    sa.Column('locataire_nom', sa.String(length=100), nullable=True),
    sa.Column('locataire_prenom', sa.String(length=100), nullable=True),
    sa.Column('locataire_email', sa.String(length=200), nullable=True),
    sa.Column('locataire_telephone', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['copropriete_id'], ['copropriete.id'], ),
    sa.ForeignKeyConstraint(['locataire_civilite_id'], ['civilites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons_coproprietaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('civilite_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('coproprietaire_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['civilite_id'], ['civilites.id'], ),
    sa.ForeignKeyConstraint(['coproprietaire_id'], ['coproprietaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('coproprietaire')
    with op.batch_alter_table('emails_coproprietaires', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'coproprietaires', ['coproprietaire_id'], ['id'])

    with op.batch_alter_table('lots_coproprietaires', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'coproprietaires', ['coproprietaire_id'], ['id'])

    with op.batch_alter_table('telephones_coproprietaires', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'coproprietaires', ['coproprietaire_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telephones_coproprietaires', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'coproprietaire', ['coproprietaire_id'], ['id'])
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('lots_coproprietaires', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'coproprietaire', ['coproprietaire_id'], ['id'])

    with op.batch_alter_table('emails_coproprietaires', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'coproprietaire', ['coproprietaire_id'], ['id'])
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    op.create_table('coproprietaire',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('copropriete_id', sa.INTEGER(), nullable=False),
    sa.Column('date_acquisition', sa.DATE(), nullable=True),
    sa.Column('nom', sa.VARCHAR(length=100), nullable=True),
    sa.Column('prenom', sa.VARCHAR(length=100), nullable=True),
    sa.Column('numero_lot', sa.VARCHAR(length=50), nullable=True),
    sa.Column('nature_lot', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('est_residence_principale', sa.BOOLEAN(), nullable=True),
    sa.Column('est_loue', sa.BOOLEAN(), nullable=True),
    sa.Column('date_envoi_mail_accueil', sa.DATE(), nullable=True),
    sa.Column('lien_espace_client', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['copropriete_id'], ['copropriete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('persons_coproprietaires')
    op.drop_table('coproprietaires')
    op.drop_table('civilites')
    # ### end Alembic commands ###
